### ISSUE TITLE
Milestone: Connect with Claude.ai and ask questions about the current page content

### ISSUE THREAD

**Issue by ZacTolle** [ZacTolle/chatbot-browser-link#1]
## Setup
- [x] [98.css](https://jdan.github.io/98.css/) for design, [crxjs with Vite and Vue.js](https://crxjs.dev/vite-plugin/getting-started/vue/create-project) for extension development
- [x] Create temporary ai logo and branding (for inspo see: https://dragonball.fandom.com/wiki/Main_Page)
- [x] Setup nicer README.md
- [x] Setup a [Notion](https://notion.so/about) [Super](https://super.so/) site for documentation

## Milestone - It connects and you can ask questions about the page
- [x] There is a browser extension button with an icon
- [x] #2
- [x] Submitting a message submits it to Claude
- [x] Responses from Claude are shown in response
- [x] Ask questions about the textual content
